---
# tasks file for ansible-role-zero-footprint-ruT-seedbox
- name: Set timezone
  community.general.timezone:
    name: "{{ set_timezone }}"
  become: true

- name: Add two IPv4 DNS server addresses
  community.general.nmcli:
    conn_name: "{{ ansible_default_ipv4.alias }}"
    type: ethernet
    dns4:
      - 8.8.8.8
      - 8.8.4.4
    state: present
  become: true
  when: set_google_dns

- name: Create a directory structure
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/{{ item }}"
    state: directory
  loop:
    - .Session
    - site
    - site/.WatchAPPZ
    - site/.WatchGAMES
    - site/.WatchMISC
    - site/.WatchMP3
    - site/.WatchTV-HD
    - site/.WatchTV-SD
    - site/.WatchMOVIES-HD
    - site/.WatchMOVIES-SD
    - site/.WatchXXX
    - site/APPZ
    - site/GAMES
    - site/MISC
    - site/MP3
    - site/TV-HD
    - site/TV-SD
    - site/MOVIES-HD
    - site/MOVIES-SD
    - site/XXX
    - site/UPLOAD

- name: Change home folder permissions
  ansible.builtin.file:
    path: /home/{{ ansible_user }}
    mode: 0711

- name: Remove unnecessary motd
  ansible.builtin.file:
    path: "/etc/motd.d/{{ item }}"
    state: absent
  become: true
  loop:
    - "cockpit"
    - "insights-client"

- name: Add cleanup cron
  ansible.builtin.cron:
    name: "Remove *.torrent files older than 120 days every 1st day of the month (at 12:00AM)"
    day: "1"
    minute: "0"
    hour: "0"
    job: "find /home/{{ ansible_user }}/site/.Watch*/*.torrent -type f -ctime +120 -delete"

- name: Add cleanup cron
  ansible.builtin.cron:
    name: "Remove site sub-folders older than 120 days every 1st day of the month (at 12:02AM)"
    day: "1"
    minute: "2"
    hour: "0"
    job: "find /home/{{ ansible_user }}/site/ -maxdepth 2 -mindepth 2 -type d -ctime +120 -exec rm -rf \"{}\" +"
    backup: true

- name: Add useful alias
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: "alias rt=\"tmux a\""
    create: yes
