---
# tasks file for ansible-role-zero-footprint-ruT-seedbox
- name: RUTORRENT | Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  become: true
  loop:
    - lighttpd
    - lighttpd-fastcgi
    - php
    - php-dom
    - php-fpm
    - php-json
    - php-mbstring
    - php-libxml
    - python3-passlib
  tags:
    - rutorrent

- name: RUTORRENT | Create a directory structure
  ansible.builtin.file:
    path: "/var/www/ruTorrent"
    state: directory
    owner: lighttpd
    group: lighttpd
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Unzip the rutorrent
  ansible.builtin.unarchive:
    src: "{{ rutorrent_dl }}"
    dest: "/var/www/ruTorrent"
    owner: lighttpd
    group: lighttpd
    remote_src: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Stat rutorrent
  ansible.builtin.stat:
    path: "/var/www/ruTorrent/ruTorrent-{{ rutorrent_dl | urlsplit('path') | basename | regex_replace('^v') | regex_replace('.tar.gz') }}"
  register: rutorrent_stat
  tags:
    - rutorrent

- name: RUTORRENT | Move rutorrent
  ansible.builtin.shell: "mv -t /var/www/ruTorrent/ /var/www/ruTorrent/ruTorrent-{{ rutorrent_dl | urlsplit('path') | basename | regex_replace('^v') | regex_replace('.tar.gz') }}/*"
  become: true
  when: rutorrent_stat.stat.exists
  tags:
    - rutorrent

- name: RUTORRENT | Remove temporary directory
  ansible.builtin.file:
    path: "/var/www/ruTorrent/ruTorrent-{{ rutorrent_dl | urlsplit('path') | basename | regex_replace('^v') | regex_replace('.tar.gz') }}"
    state: absent
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Template the configuration for rutorrent
  ansible.builtin.template:
    src: rtorrent/config.php.j2
    dest: /var/www/ruTorrent/conf/config.php
    owner: lighttpd
    group: lighttpd
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Disable unnecessary rutorrent plugins
  ansible.builtin.lineinfile:
    path: /var/www/ruTorrent/conf/plugins.ini
    line: "{{ item }}"
    create: true
    backup: true
  become: true
  loop:
    - "[_cloudflare] enabled = no"
    - "[autotools] enabled = no"
    - "[dump] enabled = no"
    - "[extratio] enabled = no"
    - "[extsearch] enabled = no"
    - "[feeds] enabled = no"
    - "[filedrop] enabled = no"
    - "[geoip] enabled = no"
    - "[history] enabled = no"
    - "[ipad] enabled = no"
    - "[lookat] enabled = no"
    - "[mediainfo] enabled = no"
    - "[ratio] enabled = no"
    - "[rss] enabled = no"
    - "[rssurlrewrite] enabled = no"
    - "[screenshots] enabled = no"
    - "[spectrogram] enabled = no"
    - "[throttle] enabled = no"
    - "[unpack] enabled = no"
    - "[uploadeta] enabled = no"
    - "[xmpp] enabled = no"
  tags:
    - rutorrent

- name: RUTORRENT | Copy the configuration for php-fpm
  ansible.builtin.copy:
    src: lighttpd/www.conf
    dest: /etc/php-fpm.d/www.conf
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Template the configuration for lighttpd
  ansible.builtin.template:
    src: lighttpd/lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Copy the configuration for lighttpd modules
  ansible.builtin.copy:
    src: lighttpd/modules.conf
    dest: /etc/lighttpd/modules.conf
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Copy the configuration for auth module
  ansible.builtin.template:
    src: lighttpd/auth.conf.j2
    dest: /etc/lighttpd/conf.d/auth.conf
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Copy the configuration for fastcgi module
  ansible.builtin.copy:
    src: lighttpd/fastcgi.conf
    dest: /etc/lighttpd/conf.d/fastcgi.conf
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Add a user to a htpasswd file and ensure permissions are set
  community.general.htpasswd:
    path: /var/www/ruTorrent/.htpasswd
    name: "{{ ansible_user }}"
    password: "{{ htpasswd }}"
    owner: root
    group: lighttpd
    mode: 0640
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | Validate the lighttpd config files
  ansible.builtin.command: "lighttpd -t -f {{ item }}"
  args:
    chdir: "/etc/lighttpd/"
  loop:
    - lighttpd.conf
    - modules.conf
    - conf.d/auth.conf
    - conf.d/fastcgi.conf
  register: command_result
  failed_when: command_result.rc != 0
  tags:
    - rutorrent
