---
# tasks file for ansible-role-zero-footprint-ruT-seedbox
- name: Remove unnecessary packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
    - cockpit
    - gcc
    - gcc-c++
    - libcurl-devel
    - make
    - ncurses-devel
    - openssl-devel
    - policycoreutils-devel
    - zlib-devel

- name: Remove unnecessary files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ xmlrpc_dl | urlsplit('path') | basename | regex_replace('.tgz') }}"
    - "{{ libtorrent_dl | urlsplit('path') | basename | regex_replace('.tar.gz') }}"
    - "{{ rtorrent_dl | urlsplit('path') | basename | regex_replace('.tar.gz') }}"

- name: Remove unnecessary SELinux files
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - rutorrent.fc
    - rutorrent.if
    - rutorrent.pp
    - rutorrent.te
    - tmux.fc
    - tmux.if
    - tmux.pp
    - tmux.te

- name: Compile the SELinux modules
  ansible.builtin.command: "dnf clean all"
  become: true

- name: Disable some services
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: "{{ item }}"
  become: true
  loop:
    - rsyslog

- name: Find /var/log all directories, exclude nginx and mysql
  ansible.builtin.find:
    paths: /var/log
    recurse: yes
    file_type: file
  become: true
  register: var_log_files

- name: Empty all var_log_files
  community.general.filesize:
    path: "{{ item.path }}"
    size: 0B
  become: true
  loop: "{{ var_log_files.files }}"
